name: Build, Push, and Deploy Power Clean Niederrhein

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
          script: |
            # Projektverzeichnis definieren
            PROJECT_DIR="$HOME/projekte/${{ github.event.repository.name }}"
            REPO_URL="https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git"

            # Projekt klonen, falls es noch nicht existiert
            if [ ! -d "$PROJECT_DIR"/.git ]; then
              # Klonen mit dem Token, falls der Ordner leer oder kein Git-Repo ist
              rm -rf "$PROJECT_DIR" # Sicherheitshalber leeren Ordner entfernen
              git clone "$REPO_URL" "$PROJECT_DIR"
            fi

            # In das Projektverzeichnis wechseln und die neuesten Änderungen holen
            cd "$PROJECT_DIR"
            git remote set-url origin "$REPO_URL"
            git pull origin master

            # Das neueste Docker-Image herunterladen
            sudo docker compose --file docker-compose.yaml pull

            # Die Anwendung mit der neuen Konfiguration und dem neuen Image starten/aktualisieren
            sudo docker compose --file docker-compose.yaml up -d

            # Alte, ungenutzte Docker-Images aufräumen
            sudo docker image prune -af
